# Default values for springboot-demoweb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: 219244194696.dkr.ecr.us-east-1.amazonaws.com/demoproject
  tag: tag
  pullPolicy: IfNotPresent
  pullSecret: ecrregistry
service:
  name: nginx
  type: NodePort
  externalPort: 8080
  internalPort: 8080
ingress:
  enabled: false
  # Used to create an Ingress record.
  hosts:
    - chart-example.local
resources: {}
