# Default values for springboot-demoweb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: 062211046697.dkr.ecr.us-east-2.amazonaws.com/springboot-demoweb
  tag: imagetag
  pullPolicy: IfNotPresent
  pullSecret: regcred
service:
  name: nginx
  type: NodePort
  externalPort: 8080
  internalPort: 8080
ingress:
  enabled: false
  # Used to create an Ingress record.
  hosts:
    - chart-example.local
resources: {}
