pipeline {
   environment {
    image = "062211046697.dkr.ecr.us-east-2.amazonaws.com/springboot-demoweb"
	version = "1.0.0.$BUILD_NUMBER"
	NAMESPACE= "springboot-demoweb"
	RELEASE_NAME = "springboot-demoweb"
	region= "us-east-2"
	cluster_name= "Cluster-avMYie8MkKMO"
	
   }
  agent {
    node {
      label 'master'
    }

  }
  stages {
    stage('Build') {
      steps {
        sh 'cd springboot-demo/demoweb && mvn package'
      }
    }
    stage('Test') {
      steps {
        sh 'cd springboot-demo/demoweb && mvn test '
      }
    }
	  
	  stage('Code Quality') {
      steps {
        sh 'cd springboot-demo/demoweb && mvn sonar:sonar -Dsonar.host.url=http://0.0.0.0:9000'
      }
    }
	  
	  
    stage('Image Build&Publish') {
      steps {
        echo 'Build Images'
        script {
           sh '''docker build -t $image:$version ./springboot-demo/demoweb/
		 $(aws ecr get-login --no-include-email --region us-east-2 | sed 's|https://||')
		docker push $image:$version
		docker rmi $image:$version
				 
		   '''
            
           }

      }
    }
	
	 stage('Approval for Deployment in K8s') {
       steps {
            script {
              timeout(time: 10, unit: 'MINUTES') {
                input(id: "Deploy in K8s", message: "Do You want to proceed further for deployment in k8s", ok: 'Deploy')
              }
            }
        }
    }
	
	stage('Deploy in K8s') {
       steps {
             sh """
	     echo " Update the kubeconfig"
	     aws eks --region $region update-kubeconfig --name $cluster_name
	     echo "Changing values file for built tag $version"
	     cd springboot-demo/demoweb/charts/springboot-demoweb
	     sed -i 's/imagetag/$version/' values.yaml
	     helm upgrade -n $NAMESPACE $RELEASE_NAME .
	     """
        }
    }
	  
  }
 /**   post {
    success {
      emailext (
          subject: "SUCCESSFUL: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
          body: """<p>SUCCESSFUL: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>
            <p>Check console output;<a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a></p>""",
          to: 'rajeev.k9937@gmail.com'
        )
    }

    failure {
      
      emailext (
          subject: "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
          body: """<p>FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>
            <p>Check console output at &QUOT;<a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a>&QUOT;</p>""",
          to: 'rajeev.k9937@gmail.com'
        )
    }
  } **/
}
